### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/synpp#33]
I think it would be nice to clean up the configuration format a bit. I imagine something like this:

```yaml
synpp:
  working_directory: /path/to/working_directory

  processes: 4

  run:
    - stage1
    - stage2
    - etc

population:
  settings:
    hts: entd
    sampling_rate: 0.05

  data_path: /path/to/my/data
  output_path: /path/to/my/output

java:
  binary: /path/to/java
  memory: 14G
```

There is a `synpp` namespace which controls the execution of the pipeline, everything else is individual to the use case. All options in the `synpp` namespace should be validated for consistency and lead to early errors if something is wrong.

Note that the rest is hierarchichal. I would like to request the java binary in the pipeline as `java.binary` and other values in the form of `population.settings.hts`.
